import { Device } from '../../types/Device';
import { ProductSlider } from '../ProductSlider/ProductSlider';

const prodCardsPlug: Device[] = [{
  id: '1',
  category: 'stringqwqw',
  phoneId: 'string112',
  name: '1',
  fullPrice: 1499.99,
  price: 1499,
  screen: 'string',
  capacity: 'string',
  color: 'string',
  ram: 'string',
  year: 1984,
  image: 'string',
},
{
  id: '1',
  category: 'string',
  phoneId: 'string',
  name: '2',
  fullPrice: 1499.99,
  price: 1499,
  screen: 'string',
  capacity: 'string',
  color: 'string',
  ram: 'string',
  year: 1984,
  image: 'string',
},
{
  id: '1',
  category: 'string',
  phoneId: 'string',
  name: '3',
  fullPrice: 1499.99,
  price: 1499,
  screen: 'string',
  capacity: 'string',
  color: 'string',
  ram: 'string',
  year: 1984,
  image: 'string',
},
{
  id: '1',
  category: 'string',
  phoneId: 'string',
  name: '4',
  fullPrice: 1499.99,
  price: 1499,
  screen: 'string',
  capacity: 'string',
  color: 'string',
  ram: 'string',
  year: 1984,
  image: 'string',
},
{
  id: '1',
  category: 'string',
  phoneId: 'string',
  name: '5',
  fullPrice: 1499.99,
  price: 1499,
  screen: 'string',
  capacity: 'string',
  color: 'string',
  ram: 'string',
  year: 1984,
  image: 'string',
},
{
  id: '1',
  category: 'string',
  phoneId: 'string',
  name: '6',
  fullPrice: 1499.99,
  price: 1499,
  screen: 'string',
  capacity: 'string',
  color: 'string',
  ram: 'string',
  year: 1984,
  image: 'string',
},
{
  id: '1',
  category: 'string',
  phoneId: 'string',
  name: '7',
  fullPrice: 1499.99,
  price: 1499,
  screen: 'string',
  capacity: 'string',
  color: 'string',
  ram: 'string',
  year: 1984,
  image: 'string',
},
{
  id: '1',
  category: 'string',
  phoneId: 'string',
  name: '8',
  fullPrice: 1499.99,
  price: 1499,
  screen: 'string',
  capacity: 'string',
  color: 'string',
  ram: 'string',
  year: 1984,
  image: 'string',
},
];

export const Recomended = () => {
  return (
    <div className="recomended">
      <ProductSlider products={prodCardsPlug} />
    </div>
  );
};
